"""Added DocumentType to Document

Revision ID: efffe3e992b5
Revises: 273cb098556f
Create Date: 2024-09-08 01:20:14.117822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efffe3e992b5'
down_revision = '273cb098556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DocumentType', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('Author_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Document', schema=None) as batch_op:
        batch_op.drop_column('Author_id')
        batch_op.drop_column('DocumentType')

    # ### end Alembic commands ###
